(13) Registo através de redes sociais
greenIy/greenly pull request #35
Opened 2022-05-11 15:18 UTC by xsu1010

### Adições:
- Registo/Login através de redes sociais
  - Backend
    - Adição de estratégias no passport.js para login/registo com Google e Facebook
    - Adição de rotas no servidor para uso das mesmas
  - Frontend
    - Adição de funções nos componentes de LoginForm e RegisterConsumer para login/registo com Google e Facebook
    - Adição de módulo do API do facebook (facebook_oAuth.js) para invocação modular do mesmo
 
### Alterações
- Remoção dos botões de registo através de redes sociais nos forms de registo de transportador/fornecedor
- Adição de uma nova tabela (Credentials)
  - Credenciais passam a ser armazenadas com entradas `provider` + `value` em vez de `password`
    - Isto permite com que contas de diferentes fontes (redes sociais ou login básico) consigam ser armazenadas corretamente
- Adição de ficheiro de configuração de vue no client-side (`vue.config.js`)
  - Permite iniciar o servidor em modo HTTPS, requerido para o uso correto do API do Facebook
- Bugfixes
  - Alteração dos nomes dos ficheiros para as capitais corretas
  - Alteração do baseURL no client-side (http-common.js) de modo a usar o API no servidor de desenvolvimento

2022-05-11 20:15 UTC, zeval requested changes
Ver comentários

2022-05-12 13:02 UTC, zeval reviewed
Banger parece tudo bem, vê só o comment das dependências

2022-05-12 16:43 UTC, merged

2024-05-03 01:24 UTC, xsu1010 reviewed
n acredito nisto 2 anos depois

2024-05-03 01:24 UTC, xsu1010 commented on server/lib/persistence.js
> +
entrou no último commit sem querer enquanto tentava dar fix aos conflitos. fixed

2024-05-03 01:24 UTC, xsu1010 commented on client/package.json
> +    "vue-google-oauth2": "^1.5.8",
Ahhh não tava a aparecer a outra dependência ent n tava a perceber do que é que tavas a falar, fixed

2024-05-15 22:23 UTC, zev4l commented on client/src/main.js
> +    clientId: '569764819828-g3po196193avqfu9bc9puqp1ncihjipr.apps.googleusercontent.com',
Sei onde vives nunca te esqueças disso

2024-05-15 22:26 UTC, xsu1010 commented on client/src/main.js
> +    clientId: '569764819828-g3po196193avqfu9bc9puqp1ncihjipr.apps.googleusercontent.com',
🤫🤫🧏🏼